---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 10080}]

provisioner:
  name: chef_solo

platforms:
  - name: centos6

suites:
  - name: default
    run_list:
      - recipe[zabbix::default]
    attributes:
